# Generated by Django 5.0.6 on 2024-05-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0007_projectimage_projectvideo_alter_moderator_offer_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology_list',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
