# Generated by Django 5.0.6 on 2024-05-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorTechnologyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='offers/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil', models.CharField(max_length=100)),
                ('skil_img', models.ImageField(upload_to='skils/')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('expirence', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile', models.FilePathField(path='/img')),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
                ('tiktok', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('location', models.URLField(max_length=100)),
                ('skil_list', models.ManyToManyField(to='moderator.moderatortechnologylist')),
                ('offer', models.ManyToManyField(to='moderator.offer')),
            ],
        ),
        migrations.AddField(
            model_name='moderatortechnologylist',
            name='skils',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.skil'),
        ),
    ]
