# Generated by Django 5.0.6 on 2024-05-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorTechnologyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil', models.CharField(max_length=100, unique=True)),
                ('skil_img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reles_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField()),
                ('technology_list', models.ManyToManyField(to='moderator.moderatortechnologylist')),
                ('images', models.ManyToManyField(to='moderator.projectimage')),
                ('videos', models.ManyToManyField(blank=True, to='moderator.projectvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('expirence', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile', models.URLField()),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('location', models.URLField(blank=True, max_length=100, null=True)),
                ('rezyume', models.URLField(blank=True, null=True)),
                ('skil_list', models.ManyToManyField(blank=True, to='moderator.moderatortechnologylist')),
                ('offer', models.ManyToManyField(blank=True, to='moderator.offer')),
                ('projects', models.ManyToManyField(blank=True, to='moderator.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.project')),
            ],
        ),
        migrations.AddField(
            model_name='moderatortechnologylist',
            name='skils',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.skil', unique=True),
        ),
    ]
