# Generated by Django 5.0.6 on 2024-05-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='projects',
            field=models.ManyToManyField(to='project.project'),
        ),
    ]
