# Generated by Django 5.0.6 on 2024-05-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_moderator_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
