# Generated by Django 5.0.6 on 2024-05-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_alter_moderator_facebook_alter_moderator_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='skil_list',
            field=models.ManyToManyField(null=True, to='moderator.moderatortechnologylist'),
        ),
    ]
