# Generated by Django 5.0.6 on 2024-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_alter_moderator_skil_list'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='offer',
            field=models.ManyToManyField(blank=True, null=True, to='moderator.offer'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='project.project'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='skil_list',
            field=models.ManyToManyField(blank=True, null=True, to='moderator.moderatortechnologylist'),
        ),
    ]
