# Generated by Django 5.0.6 on 2024-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0006_alter_moderator_offer_alter_moderator_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.AlterField(
            model_name='moderator',
            name='offer',
            field=models.ManyToManyField(blank=True, to='moderator.offer'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='skil_list',
            field=models.ManyToManyField(blank=True, to='moderator.moderatortechnologylist'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reles_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField()),
                ('technology_list', models.ManyToManyField(to='moderator.moderatortechnologylist')),
                ('images', models.ManyToManyField(to='moderator.projectimage')),
                ('videos', models.ManyToManyField(to='moderator.projectvideo')),
            ],
        ),
        migrations.AlterField(
            model_name='moderator',
            name='projects',
            field=models.ManyToManyField(blank=True, to='moderator.project'),
        ),
    ]
