# Generated by Django 5.0.6 on 2024-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0007_projectimage_projectvideo_alter_moderator_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='image',
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='videos',
            field=models.ManyToManyField(blank=True, to='moderator.projectvideo'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
