# Generated by Django 5.0.6 on 2024-05-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0009_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
