# Generated by Django 5.0.6 on 2024-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0010_projectviewcount_delete_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
